# Uncomment the next line to define a global platform for your project
platform :ios, '12.6'

target 'GoogleAuth+Calendar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleAuth+Calendar
  pod 'GoogleSignIn'

end
